In [1]:
import pandas as pd

In [49]:
data=pd.read_csv("./rankingcard.csv")
data.drop("Unnamed: 0",axis=1,inplace=True)

In [51]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150000 entries, 0 to 149999
Data columns (total 11 columns):
 #   Column                                Non-Null Count   Dtype
---  ------                                --------------   -----
 0   SeriousDlqin2yrs                      150000 non-null  int64
 1   RevolvingUtilizationOfUnsecuredLines  150000 non-null  float64
 2   age                                   150000 non-null  int64
 3   NumberOfTime30-59DaysPastDueNotWorse  150000 non-null  int64
 4   DebtRatio                             150000 non-null  float64
 5   MonthlyIncome                         120269 non-null  float64
 6   NumberOfOpenCreditLinesAndLoans       150000 non-null  int64
 7   NumberOfTimes90DaysLate               150000 non-null  int64
 8   NumberRealEstateLoansOrLines          150000 non-null  int64
 9   NumberOfTime60-89DaysPastDueNotWorse  150000 non-null  int64
 10  NumberOfDependents                    146076 non-null  float64
dtypes: float64(4), int64(7)
memory usage: 12.6 MB

In [52]:
data.isnull().sum()

SeriousDlqin2yrs                            0
RevolvingUtilizationOfUnsecuredLines        0
age                                         0
NumberOfTime30-59DaysPastDueNotWorse        0
DebtRatio                                   0
MonthlyIncome                           29731
NumberOfOpenCreditLinesAndLoans             0
NumberOfTimes90DaysLate                     0
NumberRealEstateLoansOrLines                0
NumberOfTime60-89DaysPastDueNotWorse        0
NumberOfDependents                       3924
dtype: int64

In [53]:
#查看缺失值的比例占多少
data.isnull().mean()

SeriousDlqin2yrs                        0.000000
RevolvingUtilizationOfUnsecuredLines    0.000000
age                                     0.000000
NumberOfTime30-59DaysPastDueNotWorse    0.000000
DebtRatio                               0.000000
MonthlyIncome                           0.198207
NumberOfOpenCreditLinesAndLoans         0.000000
NumberOfTimes90DaysLate                 0.000000
NumberRealEstateLoansOrLines            0.000000
NumberOfTime60-89DaysPastDueNotWorse    0.000000
NumberOfDependents                      0.026160
dtype: float64

In [54]:
#数据的预处理，第一步：去除数据的重复值
data.drop_duplicates(inplace=True)

In [55]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 149391 entries, 0 to 149999
Data columns (total 11 columns):
 #   Column                                Non-Null Count   Dtype
---  ------                                --------------   -----
 0   SeriousDlqin2yrs                      149391 non-null  int64
 1   RevolvingUtilizationOfUnsecuredLines  149391 non-null  float64
 2   age                                   149391 non-null  int64
 3   NumberOfTime30-59DaysPastDueNotWorse  149391 non-null  int64
 4   DebtRatio                             149391 non-null  float64
 5   MonthlyIncome                         120170 non-null  float64
 6   NumberOfOpenCreditLinesAndLoans       149391 non-null  int64
 7   NumberOfTimes90DaysLate               149391 non-null  int64
 8   NumberRealEstateLoansOrLines          149391 non-null  int64
 9   NumberOfTime60-89DaysPastDueNotWorse  149391 non-null  int64
 10  NumberOfDependents                    145563 non-null  float64
dtypes: float64(4), int64(7)
memory usage: 13.7 MB

In [56]:
#再去除重复的值之后，一定要让索引更改
data.index=range(data.shape[0])
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 149391 entries, 0 to 149390
Data columns (total 11 columns):
 #   Column                                Non-Null Count   Dtype
---  ------                                --------------   -----
 0   SeriousDlqin2yrs                      149391 non-null  int64
 1   RevolvingUtilizationOfUnsecuredLines  149391 non-null  float64
 2   age                                   149391 non-null  int64
 3   NumberOfTime30-59DaysPastDueNotWorse  149391 non-null  int64
 4   DebtRatio                             149391 non-null  float64
 5   MonthlyIncome                         120170 non-null  float64
 6   NumberOfOpenCreditLinesAndLoans       149391 non-null  int64
 7   NumberOfTimes90DaysLate               149391 non-null  int64
 8   NumberRealEstateLoansOrLines          149391 non-null  int64
 9   NumberOfTime60-89DaysPastDueNotWorse  149391 non-null  int64
 10  NumberOfDependents                    145563 non-null  float64
dtypes: float64(4), int64(7)
memory usage: 12.5 MB

In [57]:
#填充缺失值
data.loc[:,"NumberOfDependents"].fillna(data.loc[:,"NumberOfDependents"].mean(),inplace=True)

In [58]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 149391 entries, 0 to 149390
Data columns (total 11 columns):
 #   Column                                Non-Null Count   Dtype
---  ------                                --------------   -----
 0   SeriousDlqin2yrs                      149391 non-null  int64
 1   RevolvingUtilizationOfUnsecuredLines  149391 non-null  float64
 2   age                                   149391 non-null  int64
 3   NumberOfTime30-59DaysPastDueNotWorse  149391 non-null  int64
 4   DebtRatio                             149391 non-null  float64
 5   MonthlyIncome                         120170 non-null  float64
 6   NumberOfOpenCreditLinesAndLoans       149391 non-null  int64
 7   NumberOfTimes90DaysLate               149391 non-null  int64
 8   NumberRealEstateLoansOrLines          149391 non-null  int64
 9   NumberOfTime60-89DaysPastDueNotWorse  149391 non-null  int64
 10  NumberOfDependents                    149391 non-null  float64
dtypes: float64(4), int64(7)
memory usage: 12.5 MB

In [59]:
#用随机森林方法来填充MonthlyIncome
from sklearn.ensemble import RandomForestRegressor
X_rfr=data.copy()
X_rfr.head()

,SeriousDlqin2yrs,RevolvingUtilizationOfUnsecuredLines,age,NumberOfTime30-59DaysPastDueNotWorse,DebtRatio,MonthlyIncome,NumberOfOpenCreditLinesAndLoans,NumberOfTimes90DaysLate,NumberRealEstateLoansOrLines,NumberOfTime60-89DaysPastDueNotWorse,NumberOfDependents
0,1,0.766127,45,2,0.802982,9120.0,13,0,6,0,2.0
1,0,0.957151,40,0,0.121876,2600.0,4,0,0,0,1.0
2,0,0.658180,38,1,0.085113,3042.0,2,1,0,0,0.0
3,0,0.233810,30,0,0.036050,3300.0,5,0,0,0,0.0
4,0,0.907239,49,1,0.024926,63588.0,7,0,1,0,0.0

In [61]:
fill_money=data.loc[:,"MonthlyIncome"]
X_rfr=X_rfr.loc[:,X_rfr.columns!="MonthlyIncome"]

In [62]:
X_rfr

,SeriousDlqin2yrs,RevolvingUtilizationOfUnsecuredLines,age,NumberOfTime30-59DaysPastDueNotWorse,DebtRatio,NumberOfOpenCreditLinesAndLoans,NumberOfTimes90DaysLate,NumberRealEstateLoansOrLines,NumberOfTime60-89DaysPastDueNotWorse,NumberOfDependents
0,1,0.766127,45,2,0.802982,13,0,6,0,2.0
1,0,0.957151,40,0,0.121876,4,0,0,0,1.0
2,0,0.658180,38,1,0.085113,2,1,0,0,0.0
3,0,0.233810,30,0,0.036050,5,0,0,0,0.0
4,0,0.907239,49,1,0.024926,7,0,1,0,0.0
...,...,...,...,...,...,...,...,...,...,...
149386,0,0.040674,74,0,0.225131,4,0,1,0,0.0
149387,0,0.299745,44,0,0.716562,4,0,1,0,2.0
149388,0,0.246044,58,0,3870.000000,18,0,1,0,0.0
149389,0,0.000000,30,0,0.000000,4,0,0,0,0.0
149390,0,0.850283,64,0,0.249908,8,0,2,0,0.0

In [63]:
Ytrain=fill_money[fill_money.notnull()]
Ytest=fill_money[fill_money.isnull()]
Xtrain=X_rfr.iloc[Ytrain.index,:]
Xtest=X_rfr.iloc[Ytest.index,:]

In [66]:
Xtrain.shape

(120170, 10)

In [67]:
rfr=RandomForestRegressor(n_estimators=100)
rfr=rfr.fit(Xtrain,Ytrain)
Ypredict=rfr.predict(Xtest)
Ypredict

array([0.12, 0.32, 0.14, ..., 0.23, 0.1 , 0.  ])

In [68]:
data.loc[data.loc[:,"MonthlyIncome"].isnull(),"MonthlyIncome"]=Ypredict

In [69]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 149391 entries, 0 to 149390
Data columns (total 11 columns):
 #   Column                                Non-Null Count   Dtype
---  ------                                --------------   -----
 0   SeriousDlqin2yrs                      149391 non-null  int64
 1   RevolvingUtilizationOfUnsecuredLines  149391 non-null  float64
 2   age                                   149391 non-null  int64
 3   NumberOfTime30-59DaysPastDueNotWorse  149391 non-null  int64
 4   DebtRatio                             149391 non-null  float64
 5   MonthlyIncome                         149391 non-null  float64
 6   NumberOfOpenCreditLinesAndLoans       149391 non-null  int64
 7   NumberOfTimes90DaysLate               149391 non-null  int64
 8   NumberRealEstateLoansOrLines          149391 non-null  int64
 9   NumberOfTime60-89DaysPastDueNotWorse  149391 non-null  int64
 10  NumberOfDependents                    149391 non-null  float64
dtypes: float64(4), int64(7)
memory usage: 12.5 MB

In [71]:
'''
日常处理异常值，我们使用箱线图或者3sigmoid法则来找到异常值（千万不要说依赖于眼睛看，我们是数据挖掘工程师，
除了业务理解，我们还要有方法）。但在银行数据中，我们希望排除的“异常值”不是一些超高或超低的数字，而是
一些不符合常理的数据：比如，收入不能为负数，但是一个超高水平的收入却是合理的，可以存在的。所以在银行
业中，我们往往就使用普通的描述性统计来观察数据的异常与否与数据的分布情况。注意，这种方法只能在特征量
有限的情况下进行，如果有几百个特征又无法成功降维或特征选择不管用，那还是用3sigmoid比较好。
'''
data.describe([0.01,0.1,0.25,0.5,0.75,0.9,0.99]).T

,count,mean,std,min,1%,10%,25%,50%,75%,90%,99%,max
SeriousDlqin2yrs,149391.0,0.066999,0.250021,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,1.0
RevolvingUtilizationOfUnsecuredLines,149391.0,6.071087,250.263672,0.0,0.0,0.003199,0.030132,0.154235,0.556494,0.978007,1.093922,50708.0
age,149391.0,52.306237,14.725962,0.0,24.0,33.000000,41.000000,52.000000,63.000000,72.000000,87.000000,109.0
NumberOfTime30-59DaysPastDueNotWorse,149391.0,0.393886,3.852953,0.0,0.0,0.000000,0.000000,0.000000,0.000000,1.000000,4.000000,98.0
DebtRatio,149391.0,354.436740,2041.843455,0.0,0.0,0.034991,0.177441,0.368234,0.875279,1275.000000,4985.100000,329664.0
MonthlyIncome,149391.0,5427.015593,13228.646352,0.0,0.0,0.180000,1800.000000,4425.000000,7416.000000,10800.000000,23250.000000,3008750.0
NumberOfOpenCreditLinesAndLoans,149391.0,8.480892,5.136515,0.0,0.0,3.000000,5.000000,8.000000,11.000000,15.000000,24.000000,58.0
NumberOfTimes90DaysLate,149391.0,0.238120,3.826165,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,3.000000,98.0
NumberRealEstateLoansOrLines,149391.0,1.022391,1.130196,0.0,0.0,0.000000,0.000000,1.000000,2.000000,2.000000,4.000000,54.0
NumberOfTime60-89DaysPastDueNotWorse,149391.0,0.212503,3.810523,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,2.000000,98.0
NumberOfDependents,149391.0,0.759863,1.101749,0.0,0.0,0.000000,0.000000,0.000000,1.000000,2.000000,4.000000,20.0

In [72]:
#由于在银行中，开户的年龄不可能是0岁，所以删除这一行数据
data=data.loc[data["age"]!=0]

In [73]:
data.describe([0.01,0.1,0.25,0.5,0.75,0.9,0.99]).T

,count,mean,std,min,1%,10%,25%,50%,75%,90%,99%,max
SeriousDlqin2yrs,149390.0,0.066999,0.250021,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,1.0
RevolvingUtilizationOfUnsecuredLines,149390.0,6.071121,250.264509,0.0,0.0,0.003199,0.030132,0.154234,0.556491,0.978007,1.093923,50708.0
age,149390.0,52.306587,14.725390,21.0,24.0,33.000000,41.000000,52.000000,63.000000,72.000000,87.000000,109.0
NumberOfTime30-59DaysPastDueNotWorse,149390.0,0.393882,3.852966,0.0,0.0,0.000000,0.000000,0.000000,0.000000,1.000000,4.000000,98.0
DebtRatio,149390.0,354.439110,2041.850084,0.0,0.0,0.034991,0.177441,0.368233,0.875294,1275.000000,4985.110000,329664.0
MonthlyIncome,149390.0,5427.011758,13228.690545,0.0,0.0,0.180000,1800.000000,4425.000000,7416.000000,10800.000000,23250.000000,3008750.0
NumberOfOpenCreditLinesAndLoans,149390.0,8.480909,5.136528,0.0,0.0,3.000000,5.000000,8.000000,11.000000,15.000000,24.000000,58.0
NumberOfTimes90DaysLate,149390.0,0.238122,3.826177,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,3.000000,98.0
NumberRealEstateLoansOrLines,149390.0,1.022384,1.130196,0.0,0.0,0.000000,0.000000,1.000000,2.000000,2.000000,4.000000,54.0
NumberOfTime60-89DaysPastDueNotWorse,149390.0,0.212504,3.810536,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,2.000000,98.0
NumberOfDependents,149390.0,0.759855,1.101748,0.0,0.0,0.000000,0.000000,0.000000,1.000000,2.000000,4.000000,20.0

In [78]:
"""
另外，有三个指标看起来很奇怪：
"NumberOfTime30-59DaysPastDueNotWorse"
"NumberOfTime60-89DaysPastDueNotWorse"
"NumberOfTimes90DaysLate"
这三个指标分别是“过去两年内出现35-59天逾期但是没有发展的更坏的次数”，“过去两年内出现60-89天逾期但是没
有发展的更坏的次数”,“过去两年内出现90天逾期的次数”。这三个指标，在99%的分布的时候依然是2，最大值却是
98，看起来非常奇怪。一个人在过去两年内逾期35~59天98次，一年6个60天，两年内逾期98次这是怎么算出来的？
我们可以去咨询业务人员，请教他们这个逾期次数是如何计算的。如果这个指标是正常的，那这些两年内逾期了98次的
客户，应该都是坏客户。在我们无法询问他们情况下，我们查看一下有多少个样本存在这种异常：
"""
data[data.loc[:,"NumberOfTimes90DaysLate"]>90].count()
#删除大于90次的
data=data[data.loc[:,"NumberOfTimes90DaysLate"]<90]

In [79]:
data

,SeriousDlqin2yrs,RevolvingUtilizationOfUnsecuredLines,age,NumberOfTime30-59DaysPastDueNotWorse,DebtRatio,MonthlyIncome,NumberOfOpenCreditLinesAndLoans,NumberOfTimes90DaysLate,NumberRealEstateLoansOrLines,NumberOfTime60-89DaysPastDueNotWorse,NumberOfDependents
0,1,0.766127,45,2,0.802982,9120.0,13,0,6,0,2.0
1,0,0.957151,40,0,0.121876,2600.0,4,0,0,0,1.0
2,0,0.658180,38,1,0.085113,3042.0,2,1,0,0,0.0
3,0,0.233810,30,0,0.036050,3300.0,5,0,0,0,0.0
4,0,0.907239,49,1,0.024926,63588.0,7,0,1,0,0.0
...,...,...,...,...,...,...,...,...,...,...,...
149386,0,0.040674,74,0,0.225131,2100.0,4,0,1,0,0.0
149387,0,0.299745,44,0,0.716562,5584.0,4,0,1,0,2.0
149388,0,0.246044,58,0,3870.000000,0.0,18,0,1,0,0.0
149389,0,0.000000,30,0,0.000000,5716.0,4,0,0,0,0.0
149390,0,0.850283,64,0,0.249908,8158.0,8,0,2,0,0.0

In [80]:
data.describe([0.01,0.1,0.25,0.5,0.75,0.9,0.99]).T

,count,mean,std,min,1%,10%,25%,50%,75%,90%,99%,max
SeriousDlqin2yrs,149165.0,0.066188,0.248612,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.00000,1.000000,1.0
RevolvingUtilizationOfUnsecuredLines,149165.0,6.078770,250.453111,0.0,0.0,0.003174,0.030033,0.153615,0.553698,0.97502,1.094061,50708.0
age,149165.0,52.331076,14.714114,21.0,24.0,33.000000,41.000000,52.000000,63.000000,72.00000,87.000000,109.0
NumberOfTime30-59DaysPastDueNotWorse,149165.0,0.246720,0.698935,0.0,0.0,0.000000,0.000000,0.000000,0.000000,1.00000,3.000000,13.0
DebtRatio,149165.0,354.963542,2043.344496,0.0,0.0,0.036385,0.178211,0.368619,0.876994,1277.30000,4989.360000,329664.0
MonthlyIncome,149165.0,5431.005509,13237.653407,0.0,0.0,0.180000,1800.000000,4438.000000,7423.000000,10800.00000,23250.000000,3008750.0
NumberOfOpenCreditLinesAndLoans,149165.0,8.493688,5.129841,0.0,1.0,3.000000,5.000000,8.000000,11.000000,15.00000,24.000000,58.0
NumberOfTimes90DaysLate,149165.0,0.090725,0.486354,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.00000,2.000000,17.0
NumberRealEstateLoansOrLines,149165.0,1.023927,1.130350,0.0,0.0,0.000000,0.000000,1.000000,2.000000,2.00000,4.000000,54.0
NumberOfTime60-89DaysPastDueNotWorse,149165.0,0.065069,0.330675,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.00000,2.000000,11.0
NumberOfDependents,149165.0,0.760325,1.102024,0.0,0.0,0.000000,0.000000,0.000000,1.000000,2.00000,4.000000,20.0

In [85]:
X=data.iloc[:,1:]
Y=data.iloc[:,0]
Y.shape

(149165,)

In [89]:
# 查看Y中不同的值的数目，看是否样本不均衡,通过结果
n_samples=X.shape[0]
n_samples_0=Y.value_counts()[0]
n_samples_1=Y.value_counts()[1]
print("样本个数：{};0占{:.2%};1占{:.2%}".format(n_samples,n_samples_0/n_samples,n_samples_1/n_samples))

样本个数：149165;0占93.38%;1占6.62%

In [92]:
#imblearn是专门用来处理不平衡数据集的库，在处理样本不均衡问题中性能高过sklearn很多
#imblearn里面也是一个个的类，也需要进行实例化，fit拟合，和sklearn用法相似,逻辑回归中使用最多的是上采样方法来平衡样本
from imblearn.over_sampling import SMOTE
sm=SMOTE(random_state=42)#实例化
X,Y=sm.fit_sample(X,Y)
n_samples_=X.shape[0]

In [93]:
n_samples_0=Y.value_counts()[0]
n_samples_1=Y.value_counts()[1]
print("样本个数：{};0占{:.2%};1占{:.2%}".format(n_samples_,n_samples_0/n_samples_,n_samples_1/n_samples_))

样本个数：278584;0占50.00%;1占50.00%

In [97]:
#分训练集和测试集
from sklearn.model_selection import train_test_split
import pandas as pd
X=pd.DataFrame(X)
Y=pd.DataFrame(Y)
X_train,X_vali,Y_train,Y_vali=train_test_split(X,Y)
model_data=pd.concat([Y_train,X_train],axis=1)
model_data.index=range(model_data.shape[0])
model_data.columns=data.columns
vail_data=pd.concat([Y_vali,X_vali],axis=1)
vail_data.index=range(vail_data.shape[0])
vail_data.columns=data.columns
model_data.to_csv("./model_data.csv")
vail_data.to_csv("./vali_data.csv")